apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-forecast-api
  namespace: ocean-forecast
  labels:
    app: ocean-forecast-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ocean-forecast-api
  template:
    metadata:
      labels:
        app: ocean-forecast-api
    spec:
      containers:
      - name: api
        image: ocean-forecast/api:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: redis-url
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: celery-broker-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: secret-key
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-forecast-worker
  namespace: ocean-forecast
  labels:
    app: ocean-forecast-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocean-forecast-worker
  template:
    metadata:
      labels:
        app: ocean-forecast-worker
    spec:
      containers:
      - name: worker
        image: ocean-forecast/api:latest
        command: ["celery", "-A", "app.scheduler.task_manager.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: redis-url
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: celery-broker-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ocean-forecast-secrets
              key: secret-key
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
